services:
  playwright:
    build: .
    ports:
      - "8002:8002"
    volumes:
      - ${OUTPUT:-./output}:/output
      - ${HOME}/.cache/uv:/root/.cache/uv
    shm_size: "2gb"
    restart: unless-stopped
    container_name: playwright
    environment:
     - SENDER_EMAIL
     - SENDER_PASSWORD
     - RECEIVER_EMAIL
